spring.application.name=voiceshield-backend
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
kakao.oauth.client-id=${KAKAO_REST_API_KEY:}
kakao.oauth.redirect-uri=${KAKAO_REDIRECT_URI:}
kakao.oauth.client-secret=${KAKAO_CLIENT_SECRET:}
