CREATE TABLE learning_histories (
    learning_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    scenario_id VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_learning_histories_scenario
        FOREIGN KEY (scenario_id) REFERENCES case_scenarios (scenario_id),
    CONSTRAINT uk_learning_histories_user_scenario
        UNIQUE (user_id, scenario_id),
    CONSTRAINT chk_learning_histories_status
        CHECK (status IN ('IN_PROGRESS', 'COMPLETE'))
);
